# Generated by Django 3.1.2 on 2021-02-24 04:56

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MstCompanys',
            fields=[
                ('CompanyName', models.CharField(blank=True, db_index=True, max_length=25, null=True, unique=True)),
                ('CompanyId', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='MstUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserId', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('UserName', models.CharField(blank=True, db_index=True, max_length=10, null=True, unique=True)),
                ('Pass', models.CharField(db_index=True, max_length=15, unique=True)),
                ('CompanyId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='management.mstcompanys')),
            ],
        ),
    ]
