# Generated by Django 3.1.2 on 2021-03-03 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_auto_20210303_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mstcompanys',
            name='CompanyId',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='mstusers',
            name='UserId',
            field=models.IntegerField(),
        ),
    ]
