# Generated by Django 3.1.2 on 2021-03-03 08:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_auto_20210303_1708'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mstcompanys',
            name='id',
        ),
        migrations.AlterField(
            model_name='mstcompanys',
            name='CompanyId',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='mstusers',
            name='UserId',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
