# Generated by Django 3.1.2 on 2021-03-03 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_auto_20210303_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mstusers',
            name='Pass',
            field=models.CharField(db_index=True, max_length=15),
        ),
    ]
