# Generated by Django 3.1.2 on 2021-03-05 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0007_auto_20210303_1741'),
    ]

    operations = [
        migrations.CreateModel(
            name='Roster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('Work_Status', models.CharField(max_length=20)),
                ('Application', models.CharField(choices=[('Paid', '有給'), ('Paid_AM_PM', '有給(午前・午後)'), ('Paid_hours', '有給(時間)'), ('Substitute_holiday', '代休'), ('Transfer_holiday', '振替休')], max_length=20)),
                ('Arrive_At_Work', models.DateTimeField()),
                ('Leave_The_Company', models.DateTimeField()),
                ('Man_Hours', models.IntegerField()),
                ('Remarks', models.TextField(max_length=500)),
            ],
        ),
    ]
