# Generated by Django 3.1.2 on 2021-03-05 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0008_roster'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('User_No', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('User_Name', models.CharField(blank=True, db_index=True, max_length=50, null=True, unique=True)),
                ('User_Name_kana', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('Gender', models.CharField(blank=True, max_length=2, null=True)),
                ('Birthday', models.DateField(blank=True, null=True)),
                ('Hire_Date', models.DateField(blank=True, null=True)),
                ('Type_Of_Contract', models.BooleanField(blank=True, db_index=True, max_length=15, null=True)),
                ('Affiliation_Department', models.BooleanField(blank=True, db_index=True, max_length=15, null=True)),
                ('Affiliation_Section', models.BooleanField(blank=True, db_index=True, max_length=15, null=True)),
                ('Position', models.CharField(blank=True, db_index=True, max_length=10, null=True)),
                ('Notices', models.TextField(max_length=1000)),
            ],
        ),
    ]
